CDDirectory/Models/CD.cs
using System.ComponentModel.DataAnnotations;

namespace CDDirectory.Models {
    public class CD {
        //properties
        public int CDId { get; set; }
        [Required(ErrorMessage = "Ange en titel")]
        [Display(Name= "Titel")]
        public string? Title { get; set; }
        [Required(ErrorMessage = "Ange en genre")]
        [Display(Name= "Genre")]
        public string? Genre { get; set; }
        [Required(ErrorMessage = "Ange en artist")]
        [Display(Name= "Artist")]
        public int ArtistId { get; set; }
        [Display(Name= "Artist")]
        public Artist? Artist { get; set; }
        [Display(Name= "Användare")]
        public int? UserId { get; set; }
        [Display(Name= "Användare")]
        public User? User { get; set; }

    }
}

CDDirectory/Controllers/CDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CDDirectory.Data;
using CDDirectory.Models;

namespace CDDirectory.Controllers
{
    public class CDController : Controller
    {
        private readonly CDContext _context;

        public CDController(CDContext context)
        {
            _context = context;
        }

// GET: CD
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.CD == null)
        {
            return Problem("Entity set 'CDContext.CD'  is null.");
        }

        var cds = from m in _context.CD
                    select m;
        cds = _context.CD.Include(c => c.Artist);

        if (!String.IsNullOrEmpty(searchString))
        {
            cds = cds
            .Include(c => c.Artist)
            .Where(s => s.Title!.Contains(searchString));
        }

        return View(await cds.ToListAsync());

            //
            //return View(await cDContext.ToListAsync());
        }

        // GET: CD/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.CD == null)
            {
                return NotFound();
            }

            var cD = await _context.CD
                .Include(c => c.Artist)
                .FirstOrDefaultAsync(m => m.CDId == id);
            if (cD == null)
            {
                return NotFound();
            }

            return View(cD);
        }

        // GET: CD/Create
        public IActionResult Create()
        {
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistId");
            ViewData["UserId"] = new SelectList(_context.Set<User>(), "UserId", "UserId");
            return View();
        }

        // POST: CD/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CDId,Title,Genre,ArtistId,UserId")] CD cD)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cD);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistId", cD.ArtistId);
            ViewData["UserId"] = new SelectList(_context.Set<User>(), "UserId", "UserId", cD.UserId);
            return View(cD);
        }

        // GET: CD/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.CD == null)
            {
                return NotFound();
            }

            var cD = await _context.CD.FindAsync(id);
            if (cD == null)
            {
                return NotFound();
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistId", cD.ArtistId);
            ViewData["UserId"] = new SelectList(_context.Set<User>(), "UserId", "UserId", cD.UserId);
            return View(cD);
        }

        // POST: CD/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CDId,Title,Genre,ArtistId,UserId")] CD cD)
        {
            if (id != cD.CDId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cD);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CDExists(cD.CDId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ArtistId"] = new SelectList(_context.Artist, "ArtistId", "ArtistId", cD.ArtistId);
            ViewData["UserId"] = new SelectList(_context.Set<User>(), "UserId", "UserId", cD.UserId);
            return View(cD);
        }

        // GET: CD/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.CD == null)
            {
                return NotFound();
            }

            var cD = await _context.CD
                .Include(c => c.Artist)
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.CDId == id);
            if (cD == null)
            {
                return NotFound();
            }

            return View(cD);
        }

        // POST: CD/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CD == null)
            {
                return Problem("Entity set 'CDContext.CD'  is null.");
            }
            var cD = await _context.CD.FindAsync(id);
            if (cD != null)
            {
                _context.CD.Remove(cD);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CDExists(int id)
        {
          return (_context.CD?.Any(e => e.CDId == id)).GetValueOrDefault();
        }
    }
}

CDDirectory/Views/CD/Create.cshtml
@model CDDirectory.Models.CD;

@{
    ViewData["Title"] = "Create";
}

<h1>Skapa</h1>

<h4>Ny CD</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtistId" class="control-label"></label>
                <select asp-for="ArtistId" class ="form-control" asp-items="ViewBag.ArtistId">
                    <option value="null">Välj artist (id)</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId">
                    <option value="null">Välj användare (id)</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Skapa" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Tillbaka till listan</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CDDirectory/Views/CD/Delete.cshtml
@model CDDirectory.Models.CD

@{
    ViewData["Title"] = "Delete";
}

<h1>Ta bort</h1>

<h3>Vill du verkligen ta bort?</h3>
<div>
    <h4>CD</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist.ArtistId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.UserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CDId" />
        <input type="submit" value="Ta bort" class="btn btn-danger" /> |
        <a asp-action="Index">Tillbaka till listan</a>
    </form>
</div>

CDDirectory/Views/CD/Details.cshtml
@model CDDirectory.Models.CD

@{
    ViewData["Title"] = "Details";
}

<h1>Detaljer</h1>

<div>
    <h4>CD</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist.ArtistId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.UserId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CDId">Ändra</a> |
    <a asp-action="Index">Tillbaka till listan</a>
</div>

CDDirectory/Views/CD/Edit.cshtml
@model CDDirectory.Models.CD

@{
    ViewData["Title"] = "Edit";
}

<h1>Ändra</h1>

<h4>CD</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CDId" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtistId" class="control-label"></label>
                <select asp-for="ArtistId" class="form-control" asp-items="ViewBag.ArtistId"></select>
                <span asp-validation-for="ArtistId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId">
                    <option value="">Välj användare</option>
                </select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Spara" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Tillbaka till listan</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CDDirectory/Views/CD/Index.cshtml
@model IEnumerable<CDDirectory.Models.CD>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista över CD</h1>

<p>
    <a asp-action="Create">Skapa ny</a>
</p>
<form asp-controller="CD" asp-action="Index" method="get">
    <p>
        Titel: <input type="text" name="SearchString" />
        <input type="submit" value="Filtrera" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artist)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Artist.Name)
            </td>
            <td>
                @if (item.UserId != null) {
                    @Html.DisplayFor(modelItem => item.UserId)
                } else {
                    <p>Ej utlånad</p>
                }
                
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CDId">Ändra</a> |
                <a asp-action="Details" asp-route-id="@item.CDId">Detaljer</a> |
                <a asp-action="Delete" asp-route-id="@item.CDId">Ta bort</a>
            </td>
        </tr>
}
    </tbody>
</table>